version: '3'
services:
  datahog:
    build: ./datahog
    ports:
      - "3000:3000"
  datahog-gateway:
    build: ./datahog-gateway
    volumes:
      - ./datahog-gateway:/app
    ports:
      - "3001:3001"
